server:
  port: 8080

downloader:
  youtube:
    videos-in-mp3:
      files-location: ${MP3_FILES_LOCATION:C:\Development\GitHub\afterlife-downloader\src\main\resources\downloads\mp3}

logging:
  level:
    cl.afterlife.downloader.client.builder: INFO