server:
 port: 8080

downloader:
    youtube:
      videos-in-mp3:
        files-location: ${MP3_FILES_LOCATION:C:\Users\garoj\Downloads\musica mimu}

logging:
  level:
    cl.afterlife.downloader.client.builder: INFO